CREATE TABLE topics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    stable_slug TEXT UNIQUE,
    status TEXT NOT NULL DEFAULT 'new',
    category TEXT,
    language TEXT,
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    main_entities JSONB DEFAULT '[]'::jsonb,
    secondary_entities JSONB DEFAULT '[]'::jsonb,
    keywords JSONB DEFAULT '[]'::jsonb,
    short_summary TEXT,
    long_summary TEXT,
    topic_markdown TEXT,
    topic_markdown_hash TEXT,
    embedding_model TEXT,
    embedding_dimension INTEGER DEFAULT 4096,
    topic_embedding VECTOR(4096),
    embedded_at TIMESTAMPTZ,
    importance_score FLOAT8 DEFAULT 0,
    confidence_score FLOAT8 DEFAULT 0,
    article_count INTEGER DEFAULT 0,
    source_count INTEGER DEFAULT 0,
    merged_into_topic_id UUID REFERENCES topics(id),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
